title: <p align="center"> Amit Ranjan </p>
logo: /assets/img/Amit PP Pic.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/amitr-cloud9/">LinkedIn</a> |
  <a href="https://github.com/AmitwaytoDS">GitHub</a>
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from real-timeFinancial data.
  Worked with RBC Capital Market team.
  <br>
  </p>
theme: jekyll-theme-minimal
